services:
  react_front_end:
    container_name: react_front_end
    build: ./front-end
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm i && npm run dev"
    volumes:
      - ./front-end:/front-end
    ports:
      - 3001:3001

  db:
    image: postgres:15.2
    container_name: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
 
  backend_rails_api:
    container_name: rails_api
    build: ./backend
    command: bash -c "cd rails-api && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/rails-api
    expose:
      - "3000"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    depends_on:
      - db
      - redis

 
  redis:
    image: redis:6.0.12-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    logging:
      driver: none

volumes:
  postgresql:
  redis:


