services:
  backend_rails_api:
    container_name: backend_rails_api
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: production
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6.0.12-alpine
    command: redis-server

volumes:
  postgresql:
  redis: