# fly.toml app configuration file generated for legratech on 2023-12-02T14:51:56-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "legratech"
  primary_region = "gig"

[build]
  dockerfile = "backend/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "performance"
  cpus = 4
  memory_mb = 8192
