services:
  backend_rails_api:
    container_name: backend_rails_api
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/
    expose:
      - "3000"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
 
  redis:
    image: redis:6.0.12-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    logging:
      driver: none

volumes:
  postgresql:
  redis: