services: 
  backend_rails_api:
    container_name: backend_rails_api
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/
    expose:
      - "8080"
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
 
volumes:
  postgresql: