name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy para EC2
      run: |
        cd /home/ec2-user/LeGraTech/backend
        git pull

        docker-compose down --rmi all
        docker-compose build
        docker-compose up 