name: CI
on: push
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-20.04
    steps:
      - name: Change to backend directory
        run: cd backend
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Analyze code
        run: bundle exec rubocop
  rspec:
    name: RSpec
    needs: rubocop
    runs-on: ubuntu-20.04
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:example@localhost:5432/db_test
    services:
      postgres:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_DB: db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Change to backend directory
        run: cd backend
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Install postgres client dependencies
        run: sudo apt-get install libpq-dev
      - name: Create database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load # ou db:structure:load ou db:migrate
      - name: Execução dos testes
        run: bundle exec rspec spec
